### ISSUE TITLE
Include a File Upload Example

### ISSUE THREAD

**Issue by dawidvdh** [bertho-zero/react-redux-universal-hot-example#10]
HI, if you could include an example with a file upload that would be really appreciated as i have been having some trouble with this.

**Comment by jahmaiosullivan** [comment]
I am running a file upload using React dropzone here: https://github.com/jahmaiosullivan/newsfeed/tree/master/src/components/ImageUpload

It turned out not to be that hard. I would be more than happy to walk you through it if you have specific questions.

**Comment by dawidvdh** [comment]
@jahmaiosullivan thank you but i should have probably been a little more specific, I need to know how to do a file upload with redux forms and also if there are any adjustments i need to make to the  [ApiClient](https://github.com/bertho-zero/react-redux-universal-hot-example/blob/master/src/helpers/ApiClient.js) in order for it to work.

**Comment by bertho-zero** [comment]
If you need to add a file to upload, you must add [multer](https://github.com/expressjs/multer) to express that can handle multipart/form-data.
Then you need tweak ApiClient so that it can send files.
And finally you can use [react-dropzone](https://github.com/okonet/react-dropzone) with [redux-form](https://github.com/erikras/redux-form/).

I made you a complete example on the [upload branch](https://github.com/bertho-zero/react-redux-universal-hot-example/tree/upload). (It's accessible from /upload)
You can view changes [here](https://github.com/bertho-zero/react-redux-universal-hot-example/compare/master...bertho-zero:upload).

**Comment by geppetto-puppeteer** [comment]
I'm Building on OSX-Sierra And Centos - /upload Does Not Work! I've Checked "https://react-hot-example.herokuapp.com/upload" - Does Not Work There Either - All Branches After fix: "pin feathers-hooks-common to 3.7.1" Fail for Me!
