### ISSUE TITLE
Feathers

### ISSUE THREAD

**Issue by Evanion** [bertho-zero/react-redux-universal-hot-example#13]
Nice to see an updated repo. And I like your selection of feathers, been using for another project.

But... ;)
I think it would make more sense to limit the integration to the feathers client, and include [saiichihashimoto/feathers-react-redux](https://github.com/saiichihashimoto/feathers-react-redux) instead of baking both client and server in to the same repo, as larger projects often separate them in to separate repos. And It would make it easier to strip out feathers for those that might want to use other frameworks like LoopBack or Sails, (or just plain express).

**Comment by bertho-zero** [comment]
Hello,
Thank you, I looked saiichihashimoto/feathers-react-redux but the doc is really small and I still do not see interest in integrating such a library.

The only dependencies feathers on the client side are:
- the [src/app.js](https://github.com/bertho-zero/react-redux-universal-hot-example/blob/master/src/app.js) file
- in actions of reducers instead of using `app.service( 'theservice').create(data)`, you must use `client => client.post('/theservice', { data })`, for example

For me the addition of this package only adds a dependency that is not necessary, it will not allow to me to withdraw more easily feathers.
Moreover I have already created a [basic-api branch](https://github.com/bertho-zero/react-redux-universal-hot-example/tree/basic-api) for those who are reluctant at the idea of simplifying their life.
