### ISSUE TITLE
What's the reason there is a custom feathers-authentication package?

### ISSUE THREAD

**Issue by evgenyboxer** [bertho-zero/react-redux-universal-hot-example#16]
Could you please elaborate why are you not using the package from feathers-authentication?

**Comment by bertho-zero** [comment]
Good question, before there were two socket servers, one for feathers and the original, then I make a system to log the user of socket dice socket connection with the cookie, as with express.

Feathers-socketio does not allow to give him our own server socket.io so that I had no access to the server io outside socketHandler. I needed the authentication service is already configured in express, and I could not setup middleware instantly because there was not yet feathers-socketio to set.

I just changed to use app.io (which must be used after app.listen otherwise it's not defined).

**Comment by bertho-zero** [comment]
I noticed that I get the message _'Hello World!' From server_ only by reconnecting in the hot reload.

I do not know why..

**Comment by bertho-zero** [comment]
I misread question.
For a minor change that was useless now, I am waiting for that stabilizes a bit to update to last version.
I will revert to version 0.8.0-beta-1 pending
