### ISSUE TITLE
Deploy on a nodeless server

### ISSUE THREAD

**Issue by skyrbe** [bertho-zero/react-redux-universal-hot-example#290]
Hi all,

Can anyone please help me figure out the steps to deploy the bundled files on a nodeless server. Basically, if I run npm run build, copy the generated files inside my static folder to a server, which doesn't have node installed, can I still use it? Or is a node server mandatory for this?

**Comment by MHerszak** [comment]
I am almost certain you need to have node installed.

**Comment by skyrbe** [comment]
Woah. @MHerszak : In that case, could you help me out, on a higher level, with modifying the architecture to make it nodeless. Our requirement is to not have a node setup for the configuration.

**Comment by skyrbe** [comment]
@Mhersak : We have used this framework and completed a client project. My bad, I didn't do enough research in the beginning for this. We have a week to deploy the package and now, node is apparently not an option.

**Comment by bertho-zero** [comment]
Without server node, the SSR is not possible and you lose one of the great interests of this repo. You can separate the client from the api quite easily (src/server, src/app, reducers, containers & components).

You will no longer have hot reload.
Since the html is no longer created on the server side you will have a lousy glitch at the page display, and considerable performance losses.
The benefits of SEO will be lost.
The API oriented aspect with feathers, its authentication and its client too.

**Comment by skyrbe** [comment]
@bertho-zero : Yup, I totally agree with SSR, HR and the SEO. It's just one of those people who hates node and also happens to be our client! We have already separated the api from the client, the problem is that we won't be able to run a node instance on the client's server . Any help regarding modifying the architecture to suit these needs will be really appreciated.

**Comment by MHerszak** [comment]
@skyrbe just curious, did you fix your issue? How did you do the separation?
