### ISSUE TITLE
Twitter Authentication (feathers.js)

### ISSUE THREAD

**Issue by eskilj** [bertho-zero/react-redux-universal-hot-example#313]
I am looking to integrate Twitter authentication (and possibly other third-party services). Does anyone have ideas of how this can be done in a relatively seamless way? Similar to that of the Facebook integration. 

I am using the [TwitterStrategy](https://github.com/jaredhanson/passport-twitter), and I have been able to authenticate the user. However, the callback to `http://localhost:3030/auth/twitter/callback?oauth_token=XXX&oauth_verifier=YYY` only displays the raw response JSON. If I then go back to the app, the user is authenticated and signed in with the Twitter credentials. 

My current [`api/config.js`](https://gist.github.com/eskilj/70d85cd26eab73992241e90b4b697643), and [`api/authentication/index.js`](https://gist.github.com/eskilj/6929f1e74ca77eeea977cc30c3b7f15e).

I suspect I might be missing an obvious feature of feather.js, so any help is much appreciated. I guess the missing piece is the hand-off from the api-server to the client, but I am not sure how this should be done smoothly. 

NOTE: I have seen #6 (Social Login with Passport), but I prefer to utilise feathers to the fullest.

**Comment by bertho-zero** [comment]
You should use [TwitterTokenStrategy](https://github.com/drudge/passport-twitter-token) instead of [TwitterStrategy](https://github.com/jaredhanson/passport-twitter) on server.

**Comment by synchu** [comment]
Trying to plug passport-atlassian-oauth, https://bitbucket.org/atlassianlabs/passport-atlassian-oauth/overview, to accomplish pretty mush the same as described above with not much luck. I can get redirected to my JIRA instance in order to authorize the boilerplate, however, when following with the client authentication it spits that Authentication strategy "atlassian-oauth" is not registered.

I am quite certain I am missing something as the boilerplate is quite complex (to my knowledge of the things :) ), but pulling my hair over this in the last few days.
