### ISSUE TITLE
router location is empty at server side rendering, help needed

### ISSUE THREAD

**Issue by Swapnilchavan18** [bertho-zero/react-redux-universal-hot-example#366]
I want to pass query parameters and pathname to api, but getting router.location as null, my code is as below.

@provideHooks({
  fetch: async ({ store: { dispatch, getState } , params: {postid },location }) => {
      const curr_state = getState();
      console.log(curr_state);
      //const routerlocation = curr_state.router.location; it gives null
      //console.log(routerlocation);
     /*let locationsearch = routerlocation.search;
 }
})

**Comment by bblurock** [comment]
You should use the `location` which is injected into `fetch` method already.

```
fetch: async ({ store: { dispatch, getState }, location }) => {
    console.log(location);
    ...
}
```

**Comment by bertho-zero** [comment]
If I replace https://github.com/bertho-zero/react-redux-universal-hot-example/blob/903c2ca1cff433d830b68964bc941330ea3d2959/src/containers/ChatFeathers/ChatFeathers.js#L8-L18 by
```js
@provideHooks({
  fetch: async ({ store: { dispatch, getState, inject }, params, location }) => {
    inject({ chat: reducer });

    console.log(params);
    console.log(location);
    // ...
```
that logs this on server (on http://localhost:3000/chat-feathers):
```log
{}
{ pathname: '/chat-feathers',
  search: '',
  hash: '',
  state: undefined,
  key: 'n2g60c' }
```
The query is located in location.search as a string. `router.location` of the redux store is null in `@provideHooks` because react-router has not been rendered by the server yet.
