### ISSUE TITLE
Any Plan to Support Progressive Web?

### ISSUE THREAD

**Issue by agungsb** [bertho-zero/react-redux-universal-hot-example#7]
Is there any plan in the future to support progressive web?

**Comment by bertho-zero** [comment]
I'm not familiar with the progressive web, do you know any good libraries or convenient links ?

**Comment by agungsb** [comment]
I found an interesting [repo here](https://github.com/GoogleChrome/sw-precache/tree/master/app-shell-demo) that demonstrates the progressive web. But I don't have any idea how to integrate it with this repo.

**Comment by bertho-zero** [comment]
I just found this: https://developers.google.com/web/tools/service-worker-libraries/, I'll see if it's really "without work"

**Comment by bertho-zero** [comment]
I just found this: https://developers.google.com/web/tools/service-worker-libraries/?hl=en, I'll see if it's really "without work"

**Comment by bertho-zero** [comment]
You can look my implementation of the progressive web on my [progressive branch](https://github.com/bertho-zero/react-redux-universal-hot-example/tree/progressive) ([the changes](https://github.com/bertho-zero/react-redux-universal-hot-example/compare/social-login...bertho-zero:progressive))

It's not compatible development because of weback dev server sharing files on port 3001 while the application is on port 3000. (cf: [explanation](https://github.com/goldhand/sw-precache-webpack-plugin#webpack-dev-server-support))

As it must be a html file, I generated it from a webpack [plugin](https://github.com/goldhand/sw-precache-webpack-plugin) and the helper [Html](https://github.com/bertho-zero/react-redux-universal-hot-example/blob/progressive/src/helpers/Html.js), this is the file that is used when the connection is lost.

For the cache itself, it is generated to the launch of `npm run build` through [sw-precache](https://github.com/GoogleChrome/sw-precache) and I earn about 50% in execution speed dice the second page load.

**Comment by agungsb** [comment]
Hi, glad to hear it. Nice work.

You said that it's not compatible in development. But, is it compatible in the production?

**Comment by bertho-zero** [comment]
Thank you, yes I plan soon merge, and sharing the connection between the socket and rest, and also the social login.

The service-worker works but the project is not yet fully adapted to the offline mode, I'll do that before merge on the master branch

**Comment by agungsb** [comment]
Is it true that now the project has fully supported the progressive web? If so, I think it's safe to say that this issue has to be closed.. 😄

**Comment by bertho-zero** [comment]
Yes now the progressive web supports the entire project and it's merged with master.

If you want to expand the project you have 2 ways to do it:

- [sw-precache](https://github.com/GoogleChrome/sw-precache) for static files and http requests (eg: widgets), it's [here](https://github.com/bertho-zero/react-redux-universal-hot-example/blob/master/webpack/prod.config.js#L99) that it happens
- [redux-persist](https://github.com/rt2zz/redux-persist) for the rest (eg: socket chat, auth, etc.) and which can be rendered by the server (SSR), so no requests, it's [here](https://github.com/bertho-zero/react-redux-universal-hot-example/blob/master/src/client.js#L21) that it happens
